version: "3"

services:
  www:
    build: .
    ports:
      # default public HTTP port
      - "8000:80"
    volumes:
      # mount volume for development, local changes have effect
      # without having to restart the container
      - ./dist/:/var/www/html/
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=trivialis
   
  dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=example
    depends_on:
      - db
